### PR TITLE
CLTool - Improve Linux and Windows cmake process

### PR DESCRIPTION
**Pull request by jjxtra**
The CMakeLists.txt for the cltool has been updated. It now supports the following:

- Build Linux executable
- Build Windows executable
- Create Visual Studio projects and sln file

### CODE REVIEW

**Comment by jjxtra** [comment]
Currently draft, working on fixing some Windows linker errors.

**Comment by jjxtra** [comment]
Will work on getting yamp-cpp added once I get the Windows linker error fixed

**Comment by waltjohnson** [comment]
@jjxtra Did we end up using Libusb source code or binaries?  I want to make sure we don't have a GPL license issue on our hands.

**Comment by jjxtra** [comment]
@kylemallory @waltjohnson I think this is ready for final review. I ended up bringing in yaml-cpp library for Windows. On Linux there is a package available. In either case, I had to add the header files to the repo. Let me know if the yaml-cpp header files are someplace else...

**Comment by jjxtra** [comment]
Waiting for Andrew to merge some stuff to development branch, then I will do a remerge

**Comment by jjxtra** [comment]
Merged development again, working on fixing some linker errors on Windows. Linux building fine.

**Comment by jjxtra** [comment]
@kylemallory @waltjohnson @siddirp Ready for another review on this one.

**Review by waltjohnson — APPROVED** [review]

**Pull request merged**
