### PR TITLE
LUNA-1979 add public python math lib

### PR DESCRIPTION
**Pull request by steven-fusco-inertialsense**
I moved pose.py into it's own module and published it to pip

In order to better support Windows, I've removed the symlink and changed things for relative paths

### CODE REVIEW

**Comment by steven-fusco-inertialsense** [comment]
Published here: https://pypi.org/project/inertialsense-math/

**Comment by chasekunz** [comment]
Did you symlink in the file into the old location so that all of the dependent code still works?

**Comment by steven-fusco-inertialsense** [comment]
> so that all of the dependent code still works?

yes, that's the idea, but I still think we should remove the symlink and actually use the new lib

**Comment by chasekunz** [comment]
Agree

**Review by chasekunz — APPROVED** [review]

**Review by waltjohnson — APPROVED** [review]

**Review by waltjohnson — APPROVED** [review]

**Comment by waltjohnson** [comment]
@steven-fusco-inertialsense I ran LogInspector and did the full build in Windows and Linux and it passes.  

We created a ci_hdw python project that uses this library.  It is supposed to run continuously in the background and automatically download and run the latest in the development branch.  It runs several tests in hardware to check that the system didn't break.  However, the ci_hdw project hasn't been used for over a year, since we changed buildings.  We need to resurrect that code at some point.

**Review by chasekunz — APPROVED** [review]

**Pull request merged**
