### PR TITLE
[InertialSense] Add automatic reconnection option

### PR DESCRIPTION
**Pull request by FloopCZ**
This is an attempt to add automatic reconnection to RTCM server based on #270 .
I will try to deploy and use it for a while to see how it behaves.

### CODE REVIEW

**Comment by FloopCZ** [comment]
It has been deployed on three Linux-based production vehicles for a week and all looks good. It successfully reconnects to RTK after a connection outage, therefore significantly improving the long-term reliability.

It has not been tested on Mac or Windows (where you would need to choose the right replacement for the `TCP_USER_TIMEOUT` socket option, or leave it as OS default).

**Comment by siddirp** [comment]
@FloopCZ  - We'll be testing this before merging the code. Besides our tests can you describe your test so we can replicate what you were seeing?

**Comment by FloopCZ** [comment]
@siddirp I have deployed the update on vehicles suffering from frequent internet connection outages as described in #270. Now I am monitoring the RTK differential age, making sure it reconnects after a failure and making sure the GPS status restores to RTK fix or RTK float:
image

**Review by waltjohnson — APPROVED** [review]

**Comment by waltjohnson** [comment]
@andrewpriddis Let's get this tested on our end and them merge it if all goes well.

**Review by siddirp — APPROVED** [review]

**Pull request closed without merging**
